import {
  LayoutGrid,
  ShoppingCart,
  Receipt,
  Boxes,
  ClipboardList,
  ArrowRightCircle,
  ArrowLeftCircle,
  BookOpen,
  BookUser,
  Users2,
  DatabaseBackup,
  LineChart,
  ArrowRightLeft,
  Rocket,
  BookCopy,
  DollarSign,
  BookMarked,
  Landmark,
  Search, // Added for Lot Ledger
  SlidersHorizontal,
} from 'lucide-react';
import type { NavItem } from '@/lib/types';

export const APP_NAME = "Vyapar Saathi";
export const APP_ICON = LineChart;

export const navItems: NavItem[] = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    iconName: 'LayoutGrid',
    iconColor: 'bg-indigo-500',
  },
  {
    title: 'Purchases',
    href: '/purchases',
    iconName: 'ShoppingCart',
    iconColor: 'bg-purple-600',
    shortcut: 'Alt + P',
  },
  {
    title: 'Sales',
    href: '/sales',
    iconName: 'Receipt',
    iconColor: 'bg-blue-600',
    shortcut: 'Alt + S',
  },
  {
    title: 'Location Transfer',
    href: '/location-transfer',
    iconName: 'ArrowRightLeft',
    iconColor: 'bg-cyan-600',
    shortcut: 'Alt + L',
  },
  {
    title: 'Inventory',
    href: '/inventory',
    iconName: 'Boxes',
    iconColor: 'bg-teal-600',
    shortcut: 'Alt + I',
  },
   {
    title: 'Outstanding',
    href: '/outstanding',
    iconName: 'ClipboardList',
    iconColor: 'bg-yellow-500',
    textColor: 'text-black',
    shortcut: 'Alt + O',
  },
  {
    title: 'Stock Adjustments',
    href: '/stock-adjustments',
    iconName: 'SlidersHorizontal',
    iconColor: 'bg-gray-500',
  },
  {
    title: 'Stock Ledger',
    href: '/ledger',
    iconName: 'BookUser',
    iconColor: 'bg-red-800',
    shortcut: 'Alt + K',
  },
  {
    title: 'Accounts Ledger',
    href: '/accounts-ledger',
    iconName: 'BookCopy',
    iconColor: 'bg-teal-500',
    shortcut: 'Alt + A',
  },
  {
    title: 'Lot Ledger',
    href: '/lot-ledger',
    iconName: 'Search',
    iconColor: 'bg-orange-500',
  },
  {
    title: 'Profit Analysis',
    href: '/profit-analysis',
    iconName: 'Rocket',
    iconColor: 'bg-green-500',
    shortcut: 'Alt + Shift + A',
  },
  {
    title: 'Financial Summary',
    href: '/balance-sheet',
    iconName: 'Landmark',
    iconColor: 'bg-blue-700',
  },
  {
    title: 'Payments',
    href: '/payments',
    iconName: 'ArrowRightCircle',
    iconColor: 'bg-red-600',
    shortcut: 'Alt + Shift + P',
  },
  {
    title: 'Receipts',
    href: '/receipts',
    iconName: 'ArrowLeftCircle',
    iconColor: 'bg-green-600',
    shortcut: 'Alt + R',
  },
  {
    title: 'Cash Book',
    href: '/cashbook',
    iconName: 'BookOpen',
    iconColor: 'bg-pink-600',
    shortcut: 'Alt + C',
  },
  {
    title: 'Daybook',
    href: '/daybook',
    iconName: 'BookMarked',
    iconColor: 'bg-rose-500',
    shortcut: 'Alt + D',
  },
  {
    title: 'Masters',
    href: '/masters',
    iconName: 'Users2',
    iconColor: 'bg-sky-600',
    shortcut: 'Alt + M',
  },
  {
    title: 'Backup/Restore',
    href: '/backup',
    iconName: 'DatabaseBackup',
    iconColor: 'bg-sky-500',
    shortcut: 'Alt + B',
  },
];
